### ISSUE TITLE
windows machine problem

### ISSUE THREAD

**Issue by hrgdavor** [vojtajina/sublime-OpenRelated#5]
I installed using "Control Package" but config as described on main page did not work
I used 
"open_related_patterns": [
             ["_/tpl/_.html", "_/js/_.js"]
        ]
but after debuging a bit based on your existing thread with another Win 7 user
I put 2 backslashes instead of 4 and it works ... 

"open_related_patterns": [
             ["_\tpl\_.html", "_\js\_.js"]
        ]

**Comment by vojtajina** [comment]
Added to README: https://github.com/vojtajina/sublime-OpenRelated#use-back-slashes-on-windows
